CRF/CRF/urls.py
from django.urls import path,include

urlpatterns = [
    
    path('', include('CRFAPP.urls')),
]

CRF/CRFAPP/urls.py
from django.urls import URLPattern, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from .views import *
urlpatterns=[
     path('login/',login,name="Login"),
     path('LoginCheck',login_check,name="LoginCheck"),
     path('LogOut',logout,name="Logout"),
     path('dashboard/',dashboard,name="Dashboard"),
     path('viewTask',view_tasks,name='viewTask'),
     path('AssignTask',assign_task,name="AssignTask"),
     path('Register',save_case,name="Register"),
     path('CRFDetails',detailed_page,name="CRFDetails"),
     path('display',viewall_users,name="display"),
     path('StatusUpdate',status_update,name="StatusUpdate"),
     path('ReassignTask',reassign_task,name="ReassignTask"),
     path('DetailTaskReassign',reassign_detailed_task,name="DetailTaskReassign"),
     path('ManagerActions',manager_casedetail_funs,name="ManagerActions"),
     path('ViewDoc',view_document,name="ViewDoc"),
     path('DocUpload',case_file_upload,name="DocUpload"),
     path('AllView',viewallTasks,name="AllView"),
     path('CaseDetailUpdate',detail_status_update,name="CaseDetailUpdate"),
     path('Verification',verification_cases,name="Verification")
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


app_name='CRFAPP'

CRF/templates/common/header.html
{% load  static %}

<header id="page-topbar" class="border-0">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box border-0  mt-0">
                <a href="{% url 'CRFAPP:Dashboard' %}" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{% static 'images/logo.png' %}" alt="" height="28">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/logo.png' %}" alt="" height="48"> <!--<span class="logo-txt">Minia</span>-->
                    </span>
                </a>

                <a href="{% url 'CRFAPP:Dashboard' %}" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="{% static 'images/logo.png' %}" alt="" height="24">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/logo.png' %}" alt="" height="24"> <span class="logo-txt">Minia</span>
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 header-item" id="vertical-menu-btn">
                <i class="fa fa-fw fa-bars"></i>
            </button>

            <!-- App Search-->
            <!--<form class="app-search d-none d-lg-block">
                <div class="position-relative">
                    <input type="text" class="form-control" placeholder="Search...">
                    <button class="btn btn-primary" type="button"><i class="bx bx-search-alt align-middle"></i></button>
                </div>
            </form>-->
        </div>

        <div class="d-flex">

            <div class=" d-flex align-items-center me-2 me-md-4">
                <!-- <span class="badge bg-danger rounded-pill">5</span> -->
                <!-- <a href=""><img src="{% static 'images/social-icons/instagram.png' %}" alt="instagram" class="me-2 me-md-3" height="16"></a>
                <a href=""><img src="{% static 'images/social-icons/linkedin.png' %}" alt="linkedin" class="me-2 me-md-3"  height="16"></a>
                <a href=""><img src="{% static 'images/social-icons/twitter.png' %}" alt="twitter" class="me-2 me-md-3"  height="16"></a>
                <a href=""><img src="{% static 'images/social-icons/facebook.png' %}" alt="facebook" class="me-2 me-md-3"  height="16"></a>
                <a href=""><img src="{% static 'images/social-icons/yt.png' %}" alt="youtube" class="me-2 me-md-3"  height="16"></a> -->
                
            </div>


            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item " id="page-header-user-dropdown"
                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><!--bg-soft-light border-start border-end-->
                    <span class="d-none d-xl-inline-block me-2 fw-medium">Hi, {{request.session.Name}}</span>
                    <img class="rounded-circle header-profile-user" src="{% static 'images/users/'%}{{request.session.UserName}}.png" onerror='this.src="{% static 'images/users/user.png' %}"'
                        alt="Header Avatar">
                
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end">
                    <!-- item-->
                    <a class="dropdown-item" href="#"><i class="mdi mdi-face-profile font-size-16 align-middle me-1"></i> Profile</a>
                    <!-- <a class="dropdown-item" href="auth-lock-screen.html"><i class="mdi mdi-lock font-size-16 align-middle me-1"></i> Lock Screen</a> -->
                    <div class="dropdown-divider"></div>
                    
                    <a class="dropdown-item" href="{% url 'CRFAPP:Logout' %}"><i class="mdi mdi-logout font-size-16 align-middle me-1"></i> Logout</a>
                </div>
            </div>
            
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon position-relative" id="page-header-notifications-dropdown"
                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i data-feather="bell" class="icon-lg"></i>
                    <span class="badge bg-danger rounded-pill"></span>
                </button>
               
            </div>

        </div>
    </div>
</header>

CRF/templates/common/link.html
{% load static %}
<link rel="shortcut icon" href="{% static 'images/favicon.ico'%}">

    <!-- plugin css -->
    <!--<link href="assets/libs/admin-resources/jquery.vectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet"
        type="text/css" />-->

    <!-- preloader css -->
<link rel="stylesheet" href="{% static 'css/preloader.min.css'%}" type="text/css" />

    <!-- Bootstrap Css -->
<link href="{% static 'css/bootstrap.min.css'%}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
<link href="{% static 'css/icons.min.css'%}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
<link href="{% static 'css/app.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />

CRF/templates/common/right-sidebar.html
  <!-- Right Sidebar -->
  <div class="right-bar ">
    <div data-simplebar class="h-100">
        <div class="rightbar-title d-flex align-items-center p-3">

            <h5 class="m-0 me-2">Theme Customizer</h5>

            <a href="javascript:void(0);" class="right-bar-toggle ms-auto">
                <i class="mdi mdi-close noti-icon"></i>
            </a>
        </div>

        <!-- Settings -->
        <hr class="m-0" />

        <div class="p-4">
            <h6 class="mb-3">Layout</h6>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="layout"
                    id="layout-vertical" value="vertical">
                <label class="form-check-label" for="layout-vertical">Vertical</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="layout"
                    id="layout-horizontal" value="horizontal">
                <label class="form-check-label" for="layout-horizontal">Horizontal</label>
            </div>

            <h6 class="mt-4 mb-3 pt-2">Layout Mode</h6>

            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="layout-mode"
                    id="layout-mode-light" value="light">
                <label class="form-check-label" for="layout-mode-light">Light</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="layout-mode"
                    id="layout-mode-dark" value="dark">
                <label class="form-check-label" for="layout-mode-dark">Dark</label>
            </div>

            <h6 class="mt-4 mb-3 pt-2">Layout Width</h6>

            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="layout-width"
                    id="layout-width-fuild" value="fuild" onchange="document.body.setAttribute('data-layout-size', 'fluid')">
                <label class="form-check-label" for="layout-width-fuild">Fluid</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="layout-width"
                    id="layout-width-boxed" value="boxed" onchange="document.body.setAttribute('data-layout-size', 'boxed')">
                <label class="form-check-label" for="layout-width-boxed">Boxed</label>
            </div>

            <h6 class="mt-4 mb-3 pt-2">Layout Position</h6>

            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="layout-position"
                    id="layout-position-fixed" value="fixed" onchange="document.body.setAttribute('data-layout-scrollable', 'false')">
                <label class="form-check-label" for="layout-position-fixed">Fixed</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="layout-position"
                    id="layout-position-scrollable" value="scrollable" onchange="document.body.setAttribute('data-layout-scrollable', 'true')">
                <label class="form-check-label" for="layout-position-scrollable">Scrollable</label>
            </div>

            <h6 class="mt-4 mb-3 pt-2">Topbar Color</h6>

            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="topbar-color"
                    id="topbar-color-light" value="light" onchange="document.body.setAttribute('data-topbar', 'light')">
                <label class="form-check-label" for="topbar-color-light">Light</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="topbar-color"
                    id="topbar-color-dark" value="dark" onchange="document.body.setAttribute('data-topbar', 'dark')">
                <label class="form-check-label" for="topbar-color-dark">Dark</label>
            </div>

            <h6 class="mt-4 mb-3 pt-2 sidebar-setting">Sidebar Size</h6>

            <div class="form-check sidebar-setting">
                <input class="form-check-input" type="radio" name="sidebar-size"
                    id="sidebar-size-default" value="default" onchange="document.body.setAttribute('data-sidebar-size', 'lg')">
                <label class="form-check-label" for="sidebar-size-default">Default</label>
            </div>
            <div class="form-check sidebar-setting">
                <input class="form-check-input" type="radio" name="sidebar-size"
                    id="sidebar-size-compact" value="compact" onchange="document.body.setAttribute('data-sidebar-size', 'md')">
                <label class="form-check-label" for="sidebar-size-compact">Compact</label>
            </div>
            <div class="form-check sidebar-setting">
                <input class="form-check-input" type="radio" name="sidebar-size"
                    id="sidebar-size-small" value="small" onchange="document.body.setAttribute('data-sidebar-size', 'sm')">
                <label class="form-check-label" for="sidebar-size-small">Small (Icon View)</label>
            </div>

            <h6 class="mt-4 mb-3 pt-2 sidebar-setting">Sidebar Color</h6>

            <div class="form-check sidebar-setting">
                <input class="form-check-input" type="radio" name="sidebar-color"
                    id="sidebar-color-light" value="light" onchange="document.body.setAttribute('data-sidebar', 'light')">
                <label class="form-check-label" for="sidebar-color-light">Light</label>
            </div>
            <div class="form-check sidebar-setting">
                <input class="form-check-input" type="radio" name="sidebar-color"
                    id="sidebar-color-dark" value="dark" onchange="document.body.setAttribute('data-sidebar', 'dark')">
                <label class="form-check-label" for="sidebar-color-dark">Dark</label>
            </div>
            <div class="form-check sidebar-setting">
                <input class="form-check-input" type="radio" name="sidebar-color"
                    id="sidebar-color-brand" value="brand" onchange="document.body.setAttribute('data-sidebar', 'brand')">
                <label class="form-check-label" for="sidebar-color-brand">Brand</label>
            </div>

            <h6 class="mt-4 mb-3 pt-2">Direction</h6>

            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="layout-direction"
                    id="layout-direction-ltr" value="ltr">
                <label class="form-check-label" for="layout-direction-ltr">LTR</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="layout-direction"
                    id="layout-direction-rtl" value="rtl">
                <label class="form-check-label" for="layout-direction-rtl">RTL</label>
            </div>

        </div>

    </div> <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->

CRF/templates/common/scripts.html
{% load static %}
<script src="{% static 'libs/jquery/jquery.min.js'%}" ></script>
<script src="{% static 'libs/bootstrap/js/bootstrap.bundle.min.js'%}" ></script>
<script src="{% static 'libs/metismenu/metisMenu.min.js'%}" ></script>
<script src="{% static 'libs/simplebar/simplebar.min.js'%}" ></script>
<script src="{% static 'libs/node-waves/waves.min.js'%}" ></script>
<script src="{% static 'libs/feather-icons/feather.min.js'%}" ></script>
<script src="{% static 'libs/pace-js/pace.min.js' %}"></script>
<!-- <script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script> -->

CRF/templates/common/sidebar.html
{% load  static %}
<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu border-0">

    <div data-simplebar class="h-100">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled gilroymedium-type fs-15" id="side-menu">
                <!--<li class="menu-title" data-key="t-menu">Menu</li>-->

                <li>
                    <a href="{% url 'CRFAPP:Dashboard' %}">
                        <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M20.1667 7.81004V3.64837C20.1667 2.35587 19.58 1.83337 18.1225 1.83337H14.4192C12.9617 1.83337 12.375 2.35587 12.375 3.64837V7.80087C12.375 9.10254 12.9617 9.61587 14.4192 9.61587H18.1225C19.58 9.62504 20.1667 9.10254 20.1667 7.81004Z" fill="#00A54F"/>
                            <path d="M20.1667 18.1225V14.4192C20.1667 12.9617 19.58 12.375 18.1225 12.375H14.4192C12.9617 12.375 12.375 12.9617 12.375 14.4192V18.1225C12.375 19.58 12.9617 20.1667 14.4192 20.1667H18.1225C19.58 20.1667 20.1667 19.58 20.1667 18.1225Z" fill="#00A54F"/>
                            <path d="M9.62498 7.81004V3.64837C9.62498 2.35587 9.03831 1.83337 7.58081 1.83337H3.87748C2.41998 1.83337 1.83331 2.35587 1.83331 3.64837V7.80087C1.83331 9.10254 2.41998 9.61587 3.87748 9.61587H7.58081C9.03831 9.62504 9.62498 9.10254 9.62498 7.81004Z" fill="#00A54F"/>
                            <path d="M9.62498 18.1225V14.4192C9.62498 12.9617 9.03831 12.375 7.58081 12.375H3.87748C2.41998 12.375 1.83331 12.9617 1.83331 14.4192V18.1225C1.83331 19.58 2.41998 20.1667 3.87748 20.1667H7.58081C9.03831 20.1667 9.62498 19.58 9.62498 18.1225Z" fill="#00A54F"/>
                        </svg>
                            
                    
                        <span data-key="t-dashboard">Dashboard</span>
                    </a>
                </li>

                <!-- <li>
                    <a href="" >
                     
                        <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M16.5 6.56338C16.445 6.55421 16.3808 6.55421 16.3258 6.56338C15.0608 6.51754 14.0525 5.48171 14.0525 4.19838C14.0525 2.88754 15.1067 1.83337 16.4175 1.83337C17.7283 1.83337 18.7825 2.89671 18.7825 4.19838C18.7733 5.48171 17.765 6.51754 16.5 6.56338Z" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M15.5558 13.2367C16.8117 13.4476 18.1958 13.2276 19.1675 12.5767C20.46 11.7151 20.46 10.3034 19.1675 9.44173C18.1867 8.7909 16.7842 8.57089 15.5283 8.79089" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M5.4725 6.56338C5.5275 6.55421 5.59167 6.55421 5.64667 6.56338C6.91167 6.51754 7.92 5.48171 7.92 4.19838C7.92 2.88754 6.86584 1.83337 5.555 1.83337C4.24417 1.83337 3.19 2.89671 3.19 4.19838C3.19917 5.48171 4.2075 6.51754 5.4725 6.56338Z" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M6.41667 13.2367C5.16084 13.4476 3.77667 13.2276 2.80501 12.5767C1.51251 11.7151 1.51251 10.3034 2.80501 9.44173C3.78584 8.7909 5.18834 8.57089 6.44417 8.79089" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M11 13.4108C10.945 13.4016 10.8808 13.4016 10.8258 13.4108C9.56082 13.365 8.55249 12.3291 8.55249 11.0458C8.55249 9.73495 9.60666 8.68079 10.9175 8.68079C12.2283 8.68079 13.2825 9.74412 13.2825 11.0458C13.2733 12.3291 12.265 13.3741 11 13.4108Z" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M8.33247 16.2983C7.03997 17.16 7.03997 18.5717 8.33247 19.4333C9.79914 20.4142 12.2008 20.4142 13.6675 19.4333C14.96 18.5717 14.96 17.16 13.6675 16.2983C12.21 15.3267 9.79914 15.3267 8.33247 16.2983Z" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                            
                        <span data-key="t-clients">All Clients</span>
                    </a>
                    
                </li> -->

                <li>
                    <a href="javascript: void(0);" class="has-arrow">
                     
                        <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M3.28168 4.72998H15.9684C17.49 4.72998 18.7184 5.95831 18.7184 7.47998V10.5233" stroke="#989898" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M6.17835 1.83337L3.28168 4.73002L6.17835 7.62671" stroke="#989898" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M18.7184 17.27H6.03168C4.51001 17.27 3.28168 16.0417 3.28168 14.52V11.4767" stroke="#989898" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M15.8217 20.1668L18.7184 17.2701L15.8217 14.3734" stroke="#989898" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                            
                            
                        <span data-key="t-backOffice">Tasks</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        {%if request.session.MemberType == "SUPER USER" or request.session.MemberType == "ADMIN" %}
                        <li> <a  href="{% url 'CRFAPP:AssignTask' %}" >Assign Task</a></li>
                        {%endif%}
                        <li> <a  href="{% url 'CRFAPP:AllView' %}" >View All</a></li>
                        
                        
                    </ul>
                </li>


                
             
             
                

         
                <li>
                    <a  href="{% url 'CRFAPP:Logout' %}" >
                    
                        <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M8.15833 6.92997C8.44249 3.62997 10.1383 2.28247 13.8508 2.28247H13.97C18.0675 2.28247 19.7083 3.9233 19.7083 8.0208V13.9975C19.7083 18.095 18.0675 19.7358 13.97 19.7358H13.8508C10.1658 19.7358 8.46999 18.4066 8.16749 15.1616" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M1.83331 11H13.64" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M11.5958 7.9292L14.6667 11L11.5958 14.0709" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg> 
                            
                        <span data-key="t-logout">Logout</span>
                    </a>
                    
                </li>



            </ul>
           

            <!--<div class="card sidebar-alert border-0 text-center mx-4 mb-0 mt-5">
                <div class="card-body">
                    <img src="assets/images/giftbox.png" alt="">
                    <div class="mt-4">
                        <h5 class="alertcard-title font-size-16">Unlimited Access</h5>
                        <p class="font-size-13">Upgrade your plan from a Free trial, to select ‘Business Plan’.</p>
                        <a href="#!" class="btn btn-primary mt-2">Upgrade Now</a>
                    </div>
                </div>
            </div>-->
        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->
<!--Popup salesperfomance-->