CRF/CRF/urls.py
from django.urls import path,include

urlpatterns = [
    
    path('', include('CRFAPP.urls')),
]

CRF/CRFAPP/urls.py
from django.urls import URLPattern, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from .views import *
urlpatterns=[
     path('login/',login,name="Login"),
     path('LoginCheck',login_check,name="LoginCheck"),
     path('LogOut',logout,name="Logout"),
     path('dashboard/',dashboard,name="Dashboard"),
     path('viewTask',view_tasks,name='viewTask'),
     path('AssignTask',assign_task,name="AssignTask"),
     path('Register',save_case,name="Register"),
     path('CRFDetails',detailed_page,name="CRFDetails"),
     path('display',viewall_users,name="display"),
     path('StatusUpdate',status_update,name="StatusUpdate"),
     path('ReassignTask',reassign_task,name="ReassignTask"),
     path('DetailTaskReassign',reassign_detailed_task,name="DetailTaskReassign"),
     path('ManagerActions',manager_casedetail_funs,name="ManagerActions"),
     path('ViewDoc',view_document,name="ViewDoc"),
     path('DocUpload',case_file_upload,name="DocUpload"),
     path('AllView',viewallTasks,name="AllView"),
     path('CaseDetailUpdate',detail_status_update,name="CaseDetailUpdate"),
     path('Verification',verification_cases,name="Verification")
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


app_name='CRFAPP'

CRF/templates/webpages/display.html
<html>
    <head>

    </head>
    <body>
        <div class="row">
    
            <div class="col-12">
               
                        
                        <div class=" px-1 table-responsive" id="seminar-rep" style="max-height: 453px;">
                            
                            <table class="table mb-0  change " >

                                <thead class="gilory-medium-type fs-16">
                                    <tr>
                                        <td>User Name</td>
                                        <td>Name</td>
                                        <td>Email</td>
                                        <td>Member Type</td>


                                    </tr>
                                    <tr>
                                        <td>Company</td>
                                        <td>Code</td>
                                    </tr>
                                </thead>
                               
                                <tbody class="gilory-regular-type fs-15 text-white" id="info-body">
                                    {%for user in users%}
                                    <tr>
                                       
                                        <td>{{user.username}}</td>
                                        <td>{{user.name}}</td>
                                        <td>{{user.email}}</td>
                                        <td>{{user.membertype}}</td>
                                       
                                    </tr>
                                    {%endfor%}
                                    {%for company in companies%}
                                    <tr>
                                       
                                        <td>{{company.company}}</td>
                                        <td>{{company.code}}</td>
                                        
                                       
                                    </tr>
                                    {%endfor%}

                                </tbody>
                              
                            </table>
                        </div>
                      
                        

               

            </div> <!-- end col -->
          



        </div>
    </body>
</html>

CRF/templates/webpages/docs.html
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8" />
    <title>Trust LNS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    {% load  static %}
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    

    <!-- preloader css -->
    <link rel="stylesheet" href="{% static 'css/preloader.min.css' %}" type="text/css" />

    <!-- Bootstrap Css -->
    <link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />
    {% include "common/scripts.html" %}
</head>

<body data-layout-mode="dark">

<!-- <body data-layout="horizontal"> -->

<!-- Begin page -->
<div id="layout-wrapper">
                                          
    

    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content  mx-auto">

        <div class="page-content mx-auto" id="sales">
            <div class="container-fluid">
                
                <div class="row">

                    <iframe src="{% static 'uploads/'%}{{imagepath}}" style="width: 100%; height: 90vh; border: 0;"></iframe>
                       
                   
                        
                        <!-- <div class=" mb-4">
                            <p class="gilroymedium-type fs-15 color-color1 mb-0">
                               From {{from}} to {{to}}</p>
                        </div> -->

                 
                        
                    </div>
                 
                </div>
                
                
                <!-- end row-->
                </div>
                
            </div>
            <!-- End Page-content -->

            
    </div>
        <!-- end main content-->

    </div>
    

    <script src="{% static 'js/app.js' %}"></script>

    </body>

    </html>

CRF/templates/webpages/login.html
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8" />
    <title>Login | Trust LNS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    {% load  static %}
    {% include "common/link.html" %}
    {% include "common/scripts.html" %}


    <!-- preloader css -->
   
</head>

<body data-layout-mode="dark">

<!-- <body data-layout="horizontal"> -->
    <div class="auth-page">
        <div class="container-fluid p-0">
            <div class="row g-0 ">
                <div class="col-xxl-9 col-lg-8 col-md-12 order-1 order-lg-0">
                    <div class=""> <!--pt-md-5 p-4 -->
              
                        <!-- <div id="circle-orbit-container" style="overflow-y:hidden ;">
    
                           
                            <div id="middle-orbit">
                              
                            </div>
                          
                        
                            <div id="outer-orbit">
                            
                            </div>
                             
                            <div id="extra-outer-orbit">
                               
                            </div>
                           
                            <div id="extra-plus-outer-orbit">
                                
                            </div>
                          
                        </div> -->
                     
                      
                    </div>
                </div>
                <div class="col-xxl-3 col-lg-4 col-md-12">
                    <div class="auth-full-page-content d-flex p-sm-5 p-4" style="background-color:#151628 ;">
                        <div class="w-100">
                            <div class="d-flex flex-column h-100">
                              
                                <div class="auth-content my-auto">
                                    <div class="text-center">
                                        <a href="index.html" class="d-block auth-logo">
                
                    
                                            <img src="{%static 'images/logo.png' %}" alt="" height="60"> <!--<span
                                                class="logo-txt">Minia</span>-->
                                        </a>
                                    </div>
                                   
                                    <form class="mt-4 pt-2 needs-validation" action="{%url 'CRFAPP:LoginCheck' %}" novalidate method="post">
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            <label class="form-label">Username</label>
                                            <input type="text" class="form-control" id="username" placeholder="Enter username" required id="validationCustom01" name="username">
                                            <!-- <div class="valid-feedback">
                                                Looks good!
                                            </div> -->
                                        </div>
                                        <div class="mb-3">
                                            <div class="d-flex align-items-start">
                                                <div class="flex-grow-1">
                                                    <label class="form-label">Password</label>
                                                </div>
                                                <div class="flex-shrink-0">
                                                    <!-- <div class="">
                                                        <a href="auth-recoverpw.html" class="text-muted">Forgot password?</a>
                                                    </div> -->
                                                </div>
                                                <!-- <div class="valid-feedback">
                                                    Looks good!
                                                </div> -->
                                            </div>
                                    
                                            <div class="input-group auth-pass-inputgroup">
                                                <input type="password" class="form-control" placeholder="Enter password"
                                                    aria-label="Password" aria-describedby="password-addon" name="password" required>
                                                
                                                    <button class="btn btn-light shadow-none ms-0" type="button"
                                                    id="password-addon"><i class="mdi mdi-eye-outline"></i></button>

                                            </div>
                                        </div>
                                       
                                     
                                        <div class="mb-3">
                                            <button class="btn btn-primary w-100 waves-effect waves-light" type="submit">Log
                                                In</button>
                                        </div>
                                        <div class="">
                                            <p class="text-danger text-center" style="font-weight: bold;">{{login_error}}</a>
                                        </div>
                                    </form>
    
                                    
                                  
                                </div>
                            
                            </div>
                        </div>
                    </div>
                    <!-- end auth full page content -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->
        </div>
        <!-- end container fluid -->
    </div>
<!-- JAVASCRIPT -->

<!-- pace js -->

<!-- password addon init -->
<script>
    
</script>
<script src="{%static 'js/pages/pass-addon.init.js' %}"></script>
<script src="{%static 'js/pages/form-validation.init.js' %}"></script>
</body>

</html>